### ISSUE TITLE
Run on Node

### ISSUE THREAD

**Issue by SunSeaAndPalms** [Microsoft/BotFramework-DirectLineJS#20]
Any way to configure it to run on node? https://github.com/reactivex/rxjs/#nodejs-usage

**Comment by billba** [comment]
Any reason to think it doesn't? I have heard from folks who have it running on servers.

**Comment by SunSeaAndPalms** [comment]
I tried to use it on Node and it goes only up-to 'Connecting'. Debugging showed that it throws
```
Error: XMLHttpRequest is not supported by your browser
    at getXMLHttpRequest (..\node_modules\rxjs\observable\dom\AjaxObservable.js:45:19)
    at Object.createXHR (..\node_modules\rxjs\observable\dom\AjaxObservable.js:93:71)
    at Object.tryCatcher (..\node_modules\rxjs\util\tryCatch.js:6:31)
    at AjaxSubscriber.send (..\node_modules\rxjs\observable\dom\AjaxObservable.js:191:50)
    at new AjaxSubscriber (..\node_modules\rxjs\observable\dom\AjaxObservable.js:180:14)
    at AjaxObservable._subscribe (..\node_modules\rxjs\observable\dom\AjaxObservable.js:115:16)
    at AjaxObservable.Observable._trySubscribe (..\node_modules\rxjs\Observable.js:57:25)
    at AjaxObservable.Observable.subscribe (..\node_modules\rxjs\Observable.js:45:27)
    at MapOperator.call (..\node_modules\rxjs\operator\map.js:54:23)
    at Observable.subscribe (..\node_modules\rxjs\Observable.js:42:22)
```

The hack from [rjxs](https://github.com/ReactiveX/rxjs/issues/2099) worked but I wonder if there is an out-of-box way?
``` 
global.XMLHttpRequest = require("xhr2");
```

**Comment by billba** [comment]
Nope, sounds like you've found a good working solution. Would love a PR to the README to help others with this problem.

**Comment by poul-kg** [comment]
@SunSeaAndPalms Hi, can you explain how you applied rxjs fix you mentioned? Do you have working DirectLine under NodeJS?

**Comment by poul-kg** [comment]
I've added 
`global.XMLHttpRequest = require("xhr2");`
to the top of my main `index.js` file, but still DirectLine connection do not work

**Comment by poul-kg** [comment]
Ok, looks like adding `global.XMLHttpRequest = require("xhr2");` to the top of the main `.js` file, can solve this issue. I wasn't sending any messages, that's why connection status was not updating.

**Comment by danmarshall** [comment]
Would be good to know if the `xhr2` trick still functions back in DOM-land. Perhaps then we can have it in master?

**Comment by billba** [comment]
I'd hate to do that, because that would make the client build bigger.
