### ISSUE TITLE
Directline creating 3 websocket connections on an expired connection

### ISSUE THREAD

**Issue by Hugo-Meiring** [microsoft/BotFramework-DirectLineJS#270]
Hi Microsoft team,

**Info**
I have an example repo that recreates our production issue:
[https://github.com/Hugo-Meiring/directline_chat](https://github.com/Hugo-Meiring/directline_chat)
See the `README.md`, I have included our console output of the issue + how to set up the project. But will try and explain here what our issue is. Also, note we use Direct Line API 3.0 on the backend side.

**Issue**
This is related to issue #124.  My question is how can I use the `directLine.connectionStatus$` subscriber to gracefully reconnect/start a new connection at the same watermark in the event of failure / token expiry/timeout.

In our production app, we have issues with bot hanging (it uses directline to communicate with our apps + website). My goal is to make our app more stable and able to recover from lost connection / expired tokens/timeouts. However, this part where directline creates 3 new web socket connections baffles me.

The code in question is:
```
value: function webSocketActivity$() {
...
return this.checkConnection().flatMap(function (_) {
```
This gets called 3 times on an expired token. Which in turn call the following code three times:

```
value: function observableWebSocket() {
...
return _Observable.Observable.create(function (subscriber) {
```

My question is looking at the example repo, how can I gracefully recover from an error and resume a chat in the case of expiry or even failure? I tried adding the watermark + conversation id earlier (not sure it is linked up anymore). It still would output 3 responses after recovery. I can manually block them but it will be painful to maintain as I need to edit the BotFramework-DirectLineJS library.

**Comment by stevkan** [comment]
@Hugo-Meiring, I'm having some difficulty building your project so, at the moment, I can't repro your issue. I'll continue to look over the code for anything obvious and speak with some colleagues while also trying to resolve the build issue I'm encountering.

Regarding that, when I run `pod install` (am I correct that this comes from CocoaPods?) I get the following message. Did you run into this and, if so, how did you resolve it? I've found a few solutions online, but none have taken yet.

```text
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/ffi-1.12.2-x64-mingw32/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library 'libcurl': The specified module could not be found.\r (LoadError)
.
Could not open library 'libcurl.dll': The specified module could not be found.\r
.
Could not open library 'libcurl.so.4': The specified module could not be found.\r
.
Could not open library 'libcurl.so.4.dll': The specified module could not be found.\r
```

**Comment by Hugo-Meiring** [comment]
I am looking into your issue. Yes `pod install` is for the cocoapods. Are you by any chance running this on a non-mac machine?

**Comment by stevkan** [comment]
I am, yes...Windows. I didn't see any indication that the project was being run on another OS. I almost asked when I started reading about CocoaPods, but I then saw there is a Windows installer so I left it alone.

Are you running this on a Mac or a Linux system? I have a Linux-based bot up and running.

**Comment by Hugo-Meiring** [comment]
My apologies @stevkan I just made a push to my repo. I forgot to mention this is a react native project. Have tested with Android it works as well as long as you update App.js line 166. 

`yarn android` to run android. You will need Android studio as well.

**Comment by Hugo-Meiring** [comment]
Also, I am running this on a Mac OSX. However, the Android one should run Linux / Windows. Will try and sit now with someone here who has a windows laptop to see if the repo works out the box on their machine and this isn't a case of it just works on my machine.

**Comment by Hugo-Meiring** [comment]
@stevkan have you been able to test on your side?

**Comment by stevkan** [comment]
@Hugo-Meiring, thank you for your patience. After pulling project updates, I'm still running into errors, just new ones now. Were you able to run it successfully on the Windows laptop?

This is what I get when I run `yarn android`. It seems I need Java. Is there a particular package / configuration (or some other) I need installed, if true?

```txt
~\source\v4\directline_chat [master ≡ +1 ~1 -0 !] 97ms> yarn android
yarn run v1.22.0
$ react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 864 file(s) to forward-jetify. Using 8 workers...
info JS server already running.
'adb' is not recognized as an internal or external command,
operable program or batch file.
info Launching emulator...
error Failed to launch emulator. Reason: No emulators found as an output of `emulator -list-avds`.
warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.
info Installing the app...

ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
    at checkExecSyncError (child_process.js:630:11)
    at execFileSync (child_process.js:648:15)
    at runOnAllDevices (C:\Users\...\source\v4\directline_chat\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

As for the iOS side, I still get the same error as previously reported.

**Comment by cleemullins** [comment]
@hugo-Meiring, @stevkan I'm planning to close this tomorrow due to inactivity. Are there updates that can be shared?

**Comment by axelsrz** [comment]
Closing due to inactivity. If error still remain please open another issue.
