### ISSUE TITLE
Crash from observableWebSocket broken connection check.

### ISSUE THREAD

**Issue by lukashaertel** [Microsoft/BotFramework-DirectLineJS#61]
https://github.com/Microsoft/BotFramework-DirectLineJS/blob/af5afc7e9dd4cb7ef5f50ae3ee9881f939556467/src/directLine.ts#L618

This line crashes the entire AsyncScheduler. In my case this is problematic because I have multiple directline connections running at the same time. A crash here kills my entire program.

I use directline in typescript with `ws@4.0.0`, `xhr2@0.1.4` and `rxjs@5.5.6`. I am using connection via secret, unique user ID per directline instance (in outgoing activities' `from` field), subscribe to `activity$` and `connectionStatus$` and properly finalize 
subscriptions with `unsubscribe` from Rx and the `end()` method from directline.

This is the stacktrace I get when running. It is inconsistently occurring, seemingly linked to the runtime of the entire program -- the exception occures more frequently as runtimes get longer.

```
.../node_modules/rxjs/scheduler/AsyncScheduler.js:45
            throw error;
            ^

Error: WebSocket is not open: readyState 2 (CLOSING)
    at WebSocket.send (.../node_modules/ws/lib/websocket.js:371:19)
    at SafeSubscriber._next (.../node_modules/botframework-directlinejs/built/directLine.js:356:100)
    at SafeSubscriber.__tryOrUnsub (.../node_modules/rxjs/Subscriber.js:239:16)
    at SafeSubscriber.next (.../node_modules/rxjs/Subscriber.js:186:22)
    at Subscriber._next (.../node_modules/rxjs/Subscriber.js:126:26)
    at Subscriber.next (.../node_modules/rxjs/Subscriber.js:90:18)
    at AsyncAction.IntervalObservable.dispatch (.../node_modules/rxjs/observable/IntervalObservable.js:70:20)
    at AsyncAction._execute (.../node_modules/rxjs/scheduler/AsyncAction.js:111:18)
    at AsyncAction.execute (.../node_modules/rxjs/scheduler/AsyncAction.js:86:26)
    at AsyncScheduler.flush (.../node_modules/rxjs/scheduler/AsyncScheduler.js:36:32)
```

**Comment by compulim** [comment]
## Note to investigator

The error is "ping Web Socket" is called while the connection is down (i.e. "not open").

## Note to fixer

We need to revisit all end/resume/error/etc conversation stories on both REST API and Web Socket side.

**Comment by orgads** [comment]
This was addressed in https://github.com/Microsoft/BotFramework-DirectLineJS/pull/132 (for https://github.com/Microsoft/BotFramework-DirectLineJS/issues/140).
